# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HXPoloHome' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HXPoloHome
  pod 'AFNetworking'
  pod 'MyLayout'
  pod 'Masonry'
  pod 'CocoaLumberjack'
  pod 'XHLaunchAd'
  pod 'CYLTabBarController'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'IGListKit', '~> 3.4.0'
  pod 'YLProgressBar', '~> 3.11.0'

  target 'HXPoloHomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HXPoloHomeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
